SELECT name, Year, ALIGN, FIRST_APPEARANCE, APPEARANCES
FROM MarvelCharacters
WHERE HAIR = 'Bald'
    AND ALIGN = 'Bad Characters'
    AND Year BETWEEN 1990 AND 1999
    AND Year IS NOT NULL
ORDER BY APPEARANCES DESC;

